### ISSUE TITLE
Is your spreadsheet still being updated?

### ISSUE THREAD

**Issue by cmarabate** [anbecker/raid-static-data-parser#2]
Hello, it seems like you may have stopped updating your spreadsheet at...
[https://docs.google.com/spreadsheets/d/16KNDJZSxabwUxaWIU7zzvsntlnAMYBYfQ-7ZZHNZLFQ/edit#gid=583240517](https://docs.google.com/spreadsheets/d/16KNDJZSxabwUxaWIU7zzvsntlnAMYBYfQ-7ZZHNZLFQ/edit#gid=583240517)

Is this true or have you just been busy lately and you still plan on keeping it up to date? It looks like the last time you updated "Champ Info" tab was 6-7-2021 (Patch 4.30).

I have become very dependent on this spreadsheet for [RaidChamps.com](https://raidchamps.com) and if you are no longer updating I would like to learn how to do it myself.

**Comment by anbecker** [comment]
Hey man - sorry I've not been updating the sheet that often. I've reached a point where RSL no longer dictates nearly as much of my life, which is lovely, but in my busyness with other things I've been a bit lax in updating it. I'll try to update the sheet more as well as this repo to get it to a more usable state.

The sheet has indeed been updated since patch 4.30 a few times - I'm not sure why you might have been seeing an older version.

Love your site by the way - I hadn't even realized you were using my sheet.

**Comment by cmarabate** [comment]
I understand that. I appreciate you taking the time to update it for me.

It appears to be updated now, thanks!

Awesome, I'm glad you like my site. It uses your sheet to create all the champ roles, display all the skill info on the champ pages, and much more 😁.
